
package com.epam.lab.task3.soap.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TicketService", targetNamespace = "http://service.soap.task3.lab.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TicketService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookTicket", targetNamespace = "http://service.soap.task3.lab.epam.com/", className = "com.epam.lab.task3.soap.service.BookTicket")
    @ResponseWrapper(localName = "bookTicketResponse", targetNamespace = "http://service.soap.task3.lab.epam.com/", className = "com.epam.lab.task3.soap.service.BookTicketResponse")
    @Action(input = "http://service.soap.task3.lab.epam.com/TicketService/bookTicketRequest", output = "http://service.soap.task3.lab.epam.com/TicketService/bookTicketResponse")
    public Long bookTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        Ticket arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.lab.task3.soap.service.Ticket
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTicketById", targetNamespace = "http://service.soap.task3.lab.epam.com/", className = "com.epam.lab.task3.soap.service.GetTicketById")
    @ResponseWrapper(localName = "getTicketByIdResponse", targetNamespace = "http://service.soap.task3.lab.epam.com/", className = "com.epam.lab.task3.soap.service.GetTicketByIdResponse")
    @Action(input = "http://service.soap.task3.lab.epam.com/TicketService/getTicketByIdRequest", output = "http://service.soap.task3.lab.epam.com/TicketService/getTicketByIdResponse")
    public Ticket getTicketById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payForTheTicket", targetNamespace = "http://service.soap.task3.lab.epam.com/", className = "com.epam.lab.task3.soap.service.PayForTheTicket")
    @ResponseWrapper(localName = "payForTheTicketResponse", targetNamespace = "http://service.soap.task3.lab.epam.com/", className = "com.epam.lab.task3.soap.service.PayForTheTicketResponse")
    @Action(input = "http://service.soap.task3.lab.epam.com/TicketService/payForTheTicketRequest", output = "http://service.soap.task3.lab.epam.com/TicketService/payForTheTicketResponse")
    public boolean payForTheTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "returnTicket", targetNamespace = "http://service.soap.task3.lab.epam.com/", className = "com.epam.lab.task3.soap.service.ReturnTicket")
    @ResponseWrapper(localName = "returnTicketResponse", targetNamespace = "http://service.soap.task3.lab.epam.com/", className = "com.epam.lab.task3.soap.service.ReturnTicketResponse")
    @Action(input = "http://service.soap.task3.lab.epam.com/TicketService/returnTicketRequest", output = "http://service.soap.task3.lab.epam.com/TicketService/returnTicketResponse")
    public boolean returnTicket(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
